[build]
compiler = "gcc"

[os]
name = "ruxos"
services = ["alloc","paging","net","fs","blkfs","select","fp_simd"]
ulib = "ruxlibc"

[os.platform]
name = "x86_64-qemu-q35"
smp = "2"
mode = "release"
log = "warn"

[os.platform.qemu]
graphic = "n"
net = "y"
blk = "y"

[[targets]]
name = "ruxos_iperf"
src = "./iperf-3.1.3/src"
src_excluded = ["main.c","t_timer.c","t_units.c","t_uuid.c"]
include_dir = "./iperf-3.1.3/src"
type = "exe"
cflags = "-Ulinux -Wno-misleading-indentation"
ldflags = "rust-lld -flavor gnu"
