[build]
compiler = "gcc"

[os]
name = "ruxos"
services = []
ulib = "ruxlibc"

[os.platform]
name = "x86_64-qemu-q35"
mode = "release"
log = "info"

[os.platform.qemu]
graphic = "y"

[[targets]]
name = "helloworld"
src = "./"
include_dir = "./"
type = "exe"
cflags = ""
linker = "rust-lld -flavor gnu"
ldflags = ""