[package]
name = "rukoskit"
version = "0.7.3"
edition = "2021"
authors = ["Zewei Yang <beichen@stu.pku.edu.cn>"]
description = "A Cargo-like build tool for building C and C++ applications"
homepage = "https://github.com/Ybeichen/rukoskit"
repository = "https://github.com/Ybeichen/rukoskit"
keywords = ["toml", "build-tool", "C++", "C", "Rust"]

[dependencies]
toml = "0.7.2"
colored = "2.0.0"
itertools="0.10.5"
sha1 = "0.10.5"
rayon = "1.7.0"
indicatif = "0.17.3"
clap = { version = "4.4.6", features = ["derive"] }