[build]
compiler = "gcc"

[os]
name = "ruxos"
services = ["alloc","paging","irq","fp_simd","multitask","fs","blkfs","net","pipe","epoll","poll","rtc","virtio-9p"]
ulib = "ruxlibc"

[os.platform]
name = "x86_64-qemu-q35"
smp = "4"
mode = "release"
log = "error"

[os.platform.qemu]
blk = "y"
net = "y"
graphic = "n"
args = "./redis-server,/v9fs/redis.conf"
v9p = "y" 
v9p_path = "./"

[[targets]]
name = "libhiredis"
src = "redis-7.0.12/deps/hiredis"
src_exclude = ["/examples","/fuzzing","/test.c","/ssl.c","/dict.c"]
include_dir = "redis-7.0.12/deps/hiredis"
type = "static"
cflags = "-std=c99 -c -O3 -fPIC -Wno-format -W -Wstrict-prototypes -Wwrite-strings -Wno-missing-field-initializers -g -ggdb -pedantic"
archive = "ar"
ldflags = "rcs"

[[targets]]
name = "liblua"
src = "redis-7.0.12/deps/lua/src"
src_exclude = ["/luac.c","/lua.c","/print.c"]
include_dir = "redis-7.0.12/deps/lua/src"
type = "static"
cflags = "-DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' -DLUA_USE_MKSTEMP -Wno-format"
archive = "ar"
ldflags = "rc"

[[targets]]
name = "libhdrhistogram"
src = "redis-7.0.12/deps/hdr_histogram"
include_dir = "redis-7.0.12/deps/hdr_histogram"
type = "static"
cflags = "-std=c99 -Os -g -Wno-format -DHDR_MALLOC_INCLUDE=\\\"hdr_redis_malloc.h\\\""
archive = "ar"
ldflags = "rcs"

[[targets]]
name = "libredis_server"
src = "redis-7.0.12/src"
src_exclude = ["/modules","/redis-benchmark.c","/ae_evport.c","/ae_epoll.c","/cli_common.c","/redis-cli.c","/ae_select.c","/ae_kqueue.c","/redisassert.c"]
include_dir = "redis-7.0.12/src"
type = "object"
cflags = "-pedantic -DREDIS_STATIC='' -std=c99 -W -Wno-missing-field-initializers -O2 -g -ggdb -Wno-format -MMD"
ldflags = "-g -ggdb -rdynamic -r"
deps = ["libhiredis","liblua","libhdrhistogram"]

[[targets]]
name = "ruxos_redis_server"
src = ""
include_dir = ""
type = "exe"
cflags = ""
linker = "rust-lld -flavor gnu"
ldflags = ""
deps = ["libredis_server"]